version: "3"

services:
  optnc :
    image : optnc/opt-temps-attente-agences-api
    container_name: optnc_api_tps_attente_kml
    ports:
      - "8080:8080"

  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    container_name: zookeeper_tps_attente_kml
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "echo", "ruok"]
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:latest
    container_name: kafka_tps_attente_kml
    ports:
      - "9094:9094"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server kafka:9094 --list"]
    depends_on: 
      - zookeeper
    environment:             
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL   
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

  red_panda:
    image: docker.redpanda.com/vectorized/console:latest
    container_name: red_panda_tps_attente_kml
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - kafka
